import arjit_singh from "./assets/Artist/arjit_singh.jfif";
import aasta_gill from "./assets/Artist/aasta_gill.jfif";
import badshah from "./assets/Artist/badshah.jfif";
import darshan_raval from "./assets/Artist/darshan_raval.jfif";
import dhvani from "./assets/Artist/dhvani.jfif";
import diljit_doshanja from "./assets/Artist/diljit_doshanja.jfif";
import sachet_tondon from "./assets/Artist/sachet_tondon.jfif";

export const artists = [
  {
    id: 0,
    name: "Arijit Singh",
    image: arjit_singh,
    tagLine: "Best Indian romantic singer",
    likes: "1.1M",
    followers: "30k",
    tags: ["romatic", "silent", "melody", "pop", "hindi_songs"],
    totalSongs: 150,
    bgColor: "#3d3273",
    songs: [
      {
        id: 1,
        singersName: "Arijit Singh",
        duration: "5:45",
        songName: "Tum Hi Ho",
        movieName: "Aashiqui 2",
      },
      {
        id: 2,
        singersName: "Arijit Singh",
        duration: "4:50",
        songName: "Channa Mereya",
        movieName: "Ae Dil Hai Mushkil",
      },
      {
        id: 3,
        singersName: "Arijit Singh",
        duration: "5:07",
        songName: "Raabta",
        movieName: "Agent Vinod",
      },
      {
        id: 4,
        singersName: "Arijit Singh",
        duration: "4:48",
        songName: "Phir Le Aya Dil",
        movieName: "Barfi!",
      },
      {
        id: 5,
        singersName: "Arijit Singh",
        duration: "4:44",
        songName: "Ae Dil Hai Mushkil",
        movieName: "Ae Dil Hai Mushkil",
      },
      {
        id: 6,
        singersName: "Arijit Singh",
        duration: "4:38",
        songName: "Gerua",
        movieName: "Dilwale",
      },
      {
        id: 7,
        singersName: "Arijit Singh",
        duration: "5:05",
        songName: "Muskurane",
        movieName: "CityLights",
      },
      {
        id: 8,
        singersName: "Arijit Singh",
        duration: "4:55",
        songName: "Sanam Re",
        movieName: "Sanam Re",
      },
      {
        id: 9,
        singersName: "Arijit Singh",
        duration: "4:20",
        songName: "Janam Janam",
        movieName: "Dilwale",
      },
      {
        id: 10,
        singersName: "Arijit Singh",
        duration: "5:30",
        songName: "Humdard",
        movieName: "Ek Villain",
      },
      {
        id: 11,
        singersName: "Arijit Singh",
        duration: "4:30",
        songName: "Agar Tum Saath Ho",
        movieName: "Tamasha",
      },
    ],
  },
  {
    id: 1,
    name: "Aasta Gill",
    image: aasta_gill,
    tagLine: "Female Indian singer",
    likes: "1.5k",
    followers: "25k",
    tags: ["romatic", "silent", "melody", "pop", "hindi_songs"],
    totalSongs: 110,
    bgColor: "#734832",
    songs: [
      {
        id: 1,
        singersName: "Aastha Gill",
        duration: "3:21",
        songName: "DJ Wale Babu",
        movieName: "N/A",
      },
      {
        id: 2,
        singersName: "Aastha Gill",
        duration: "3:33",
        songName: "Buzz",
        movieName: "N/A",
      },
      {
        id: 3,
        singersName: "Aastha Gill",
        duration: "3:16",
        songName: "Naagin",
        movieName: "N/A",
      },
      {
        id: 4,
        singersName: "Aastha Gill",
        duration: "3:12",
        songName: "Paani Paani",
        movieName: "N/A",
      },
      {
        id: 5,
        singersName: "Aastha Gill",
        duration: "3:25",
        songName: "Saara India",
        movieName: "N/A",
      },
      {
        id: 6,
        singersName: "Aastha Gill",
        duration: "2:53",
        songName: "Kamariya",
        movieName: "Stree",
      },
      {
        id: 7,
        singersName: "Aastha Gill",
        duration: "2:59",
        songName: "Abhi Toh Party Shuru Hui Hai",
        movieName: "Khoobsurat",
      },
      {
        id: 8,
        singersName: "Aastha Gill",
        duration: "3:05",
        songName: "Proper Patola",
        movieName: "Namaste England",
      },
      {
        id: 9,
        singersName: "Aastha Gill",
        duration: "3:18",
        songName: "Crazy Lady",
        movieName: "N/A",
      },
      {
        id: 10,
        singersName: "Aastha Gill",
        duration: "3:29",
        songName: "Happy Happy",
        movieName: "Blackmail",
      },
      {
        id: 11,
        singersName: "Aastha Gill",
        duration: "2:58",
        songName: "Heartless",
        movieName: "N/A",
      },
      {
        id: 12,
        singersName: "Aastha Gill",
        duration: "3:11",
        songName: "Genda Phool",
        movieName: "N/A",
      },
    ],
  },
  {
    id: 2,
    name: "Badshah",
    image: badshah,
    tagLine: "Indian pop singer",
    likes: "5.6k",
    followers: "80k",
    tags: ["romatic", "silent", "melody", "pop", "hindi_songs"],
    totalSongs: 200,
    bgColor: "#735732",
    songs: [
      {
        id: 1,
        singersName: "Badshah",
        duration: "3:21",
        songName: "DJ Wale Babu",
        movieName: "N/A",
      },
      {
        id: 2,
        singersName: "Badshah",
        duration: "3:33",
        songName: "Buzz",
        movieName: "N/A",
      },
      {
        id: 3,
        singersName: "Badshah",
        duration: "2:59",
        songName: "Abhi Toh Party Shuru Hui Hai",
        movieName: "Khoobsurat",
      },
      {
        id: 4,
        singersName: "Badshah",
        duration: "3:18",
        songName: "Genda Phool",
        movieName: "N/A",
      },
      {
        id: 5,
        singersName: "Badshah",
        duration: "3:10",
        songName: "Kala Chashma",
        movieName: "Baar Baar Dekho",
      },
      {
        id: 6,
        singersName: "Badshah",
        duration: "2:53",
        songName: "Proper Patola",
        movieName: "Namaste England",
      },
      {
        id: 7,
        singersName: "Badshah",
        duration: "3:29",
        songName: "She Move It Like",
        movieName: "N/A",
      },
      {
        id: 8,
        singersName: "Badshah",
        duration: "2:58",
        songName: "Paagal",
        movieName: "N/A",
      },
      {
        id: 9,
        singersName: "Badshah",
        duration: "3:25",
        songName: "Mercy",
        movieName: "N/A",
      },
      {
        id: 10,
        singersName: "Badshah",
        duration: "3:05",
        songName: "Heartless",
        movieName: "N/A",
      },
      {
        id: 11,
        singersName: "Badshah",
        duration: "3:12",
        songName: "Paagal",
        movieName: "N/A",
      },
      {
        id: 12,
        singersName: "Badshah",
        duration: "3:18",
        songName: "Tareefan",
        movieName: "Veere Di Wedding",
      },
    ],
  },
  {
    id: 3,
    name: "Dhavni Bhanushali",
    image: dhvani,
    tagLine: "Best Indian silent singer",
    likes: "1.0k",
    followers: "10k",
    tags: ["romatic", "silent", "melody", "pop", "hindi_songs"],
    totalSongs: 110,
    bgColor: "#637332",
    songs: [
      {
        id: 1,
        singersName: "Dhvani Bhanushali",
        duration: "3:27",
        songName: "Vaaste",
        movieName: "N/A",
      },
      {
        id: 2,
        singersName: "Dhvani Bhanushali",
        duration: "3:19",
        songName: "Leja Re",
        movieName: "N/A",
      },
      {
        id: 3,
        singersName: "Dhvani Bhanushali",
        duration: "2:50",
        songName: "Dilbar",
        movieName: "Satyameva Jayate",
      },
      {
        id: 4,
        singersName: "Dhvani Bhanushali",
        duration: "3:15",
        songName: "Psycho Saiyaan",
        movieName: "Saaho",
      },
      {
        id: 5,
        singersName: "Dhvani Bhanushali",
        duration: "3:05",
        songName: "Ishare Tere",
        movieName: "N/A",
      },
      {
        id: 6,
        singersName: "Dhvani Bhanushali",
        duration: "3:23",
        songName: "Duniya",
        movieName: "Luka Chuppi",
      },
      {
        id: 7,
        singersName: "Dhvani Bhanushali",
        duration: "3:30",
        songName: "Jeetenge Hum",
        movieName: "N/A",
      },
      {
        id: 8,
        singersName: "Dhvani Bhanushali",
        duration: "2:59",
        songName: "Nayan",
        movieName: "N/A",
      },
      {
        id: 9,
        singersName: "Dhvani Bhanushali",
        duration: "3:02",
        songName: "Mukhda Vekh Ke",
        movieName: "De De Pyaar De",
      },
      {
        id: 10,
        singersName: "Dhvani Bhanushali",
        duration: "3:45",
        songName: "Tere Naal",
        movieName: "N/A",
      },
      {
        id: 11,
        singersName: "Dhvani Bhanushali",
        duration: "3:08",
        songName: "Laila",
        movieName: "Notebook",
      },
      {
        id: 12,
        singersName: "Dhvani Bhanushali",
        duration: "3:18",
        songName: "Main Teri Hoon",
        movieName: "N/A",
      },
      {
        id: 13,
        singersName: "Dhvani Bhanushali",
        duration: "2:58",
        songName: "Na Ja Tu",
        movieName: "N/A",
      },
    ],
  },
  {
    id: 4,
    name: "Sachet Tondon",
    image: sachet_tondon,
    tagLine: "Indian romantic songs",
    likes: "3.2k",
    followers: "60k",
    tags: ["romatic", "silent", "melody", "pop", "hindi_songs"],
    totalSongs: 130,
    bgColor: "#819f33",
    songs: [
      {
        id: 1,
        singersName: "Sachet Tandon",
        duration: "4:41",
        songName: "Bekhayali",
        movieName: "Kabir Singh",
      },
      {
        id: 2,
        singersName: "Sachet Tandon",
        duration: "3:22",
        songName: "Mere Sohneya",
        movieName: "Kabir Singh",
      },
      {
        id: 3,
        singersName: "Sachet Tandon",
        duration: "3:25",
        songName: "Dilbara",
        movieName: "Pati Patni Aur Woh",
      },
      {
        id: 4,
        singersName: "Sachet Tandon",
        duration: "4:12",
        songName: "Humraah",
        movieName: "Malang",
      },
      {
        id: 5,
        singersName: "Sachet Tandon",
        duration: "3:47",
        songName: "Psycho Saiyaan",
        movieName: "Saaho",
      },
      {
        id: 6,
        singersName: "Sachet Tandon",
        duration: "3:05",
        songName: "Mere Baad",
        movieName: "Bhoot - Part One: The Haunted Ship",
      },
      {
        id: 7,
        singersName: "Sachet Tandon",
        duration: "4:05",
        songName: "Maiyya Mainu",
        movieName: "Jersey",
      },
      {
        id: 8,
        singersName: "Sachet Tandon",
        duration: "3:59",
        songName: "Ishq Mein",
        movieName: "N/A",
      },
      {
        id: 9,
        singersName: "Sachet Tandon",
        duration: "3:18",
        songName: "Pal Pal Dil Ke Paas",
        movieName: "Pal Pal Dil Ke Paas",
      },
      {
        id: 10,
        singersName: "Sachet Tandon",
        duration: "4:10",
        songName: "Muqabla",
        movieName: "Street Dancer 3D",
      },
      {
        id: 11,
        singersName: "Sachet Tandon",
        duration: "3:15",
        songName: "Baliye Re",
        movieName: "Jersey",
      },
      {
        id: 12,
        singersName: "Sachet Tandon",
        duration: "3:45",
        songName: "Kalle Kalle",
        movieName: "Chandigarh Kare Aashiqui",
      },
      {
        id: 13,
        singersName: "Sachet Tandon",
        duration: "4:20",
        songName: "Meherbani",
        movieName: "The Body",
      },
    ],
  },
  {
    id: 5,
    name: "Darshan Raval",
    image: darshan_raval,
    tagLine: "Best Indian romantic songs",
    likes: "1.2k",
    followers: "30k",
    tags: ["romatic", "silent", "melody", "pop", "hindi_songs"],
    totalSongs: 250,
    bgColor: "#733247",
    songs: [
      {
        id: 1,
        singersName: "Darshan Raval",
        duration: "3:48",
        songName: "Tera Zikr",
        movieName: "N/A",
      },
      {
        id: 2,
        singersName: "Darshan Raval",
        duration: "3:27",
        songName: "Chogada",
        movieName: "Loveyatri",
      },
      {
        id: 3,
        singersName: "Darshan Raval",
        duration: "4:11",
        songName: "Hawa Banke",
        movieName: "N/A",
      },
      {
        id: 4,
        singersName: "Darshan Raval",
        duration: "3:25",
        songName: "Kamariya",
        movieName: "Mitron",
      },
      {
        id: 5,
        singersName: "Darshan Raval",
        duration: "4:05",
        songName: "Ek Ladki Ko Dekha Toh Aisa Laga",
        movieName: "Ek Ladki Ko Dekha Toh Aisa Laga",
      },
      {
        id: 6,
        singersName: "Darshan Raval",
        duration: "3:35",
        songName: "Bhula Dunga",
        movieName: "N/A",
      },
      {
        id: 7,
        singersName: "Darshan Raval",
        duration: "3:52",
        songName: "Tera Ban Jaunga",
        movieName: "Kabir Singh",
      },
      {
        id: 8,
        singersName: "Darshan Raval",
        duration: "3:45",
        songName: "Tu Mileya",
        movieName: "N/A",
      },
      {
        id: 9,
        singersName: "Darshan Raval",
        duration: "3:37",
        songName: "Asal Mein",
        movieName: "N/A",
      },
      {
        id: 10,
        singersName: "Darshan Raval",
        duration: "3:58",
        songName: "Mehrama",
        movieName: "Love Aaj Kal",
      },
      {
        id: 11,
        singersName: "Darshan Raval",
        duration: "3:49",
        songName: "Kaash Aisa Hota",
        movieName: "N/A",
      },
      {
        id: 12,
        singersName: "Darshan Raval",
        duration: "4:02",
        songName: "Dil Mera Blast",
        movieName: "N/A",
      },
      {
        id: 13,
        singersName: "Darshan Raval",
        duration: "3:55",
        songName: "Main Woh Chand",
        movieName: "Teraa Surroor",
      },
    ],
  },
  {
    id: 6,
    name: "Diljit Dosanjha",
    image: diljit_doshanja,
    tagLine: "Best Indian punjabi songs",
    likes: "1.2k",
    followers: "30k",
    tags: ["romatic", "silent", "melody", "pop", "hindi_songs"],
    totalSongs: 210,
    bgColor: "#733232",
    songs: [
      {
        id: 1,
        singersName: "Diljit Dosanjh",
        duration: "3:12",
        songName: "Laembadgini",
        movieName: "N/A",
      },
      {
        id: 2,
        singersName: "Diljit Dosanjh",
        duration: "3:45",
        songName: "Do You Know",
        movieName: "N/A",
      },
      {
        id: 3,
        singersName: "Diljit Dosanjh",
        duration: "4:01",
        songName: "5 Taara",
        movieName: "N/A",
      },
      {
        id: 4,
        singersName: "Diljit Dosanjh",
        duration: "3:40",
        songName: "Proper Patola",
        movieName: "Namaste England",
      },
      {
        id: 5,
        singersName: "Diljit Dosanjh",
        duration: "3:25",
        songName: "Putt Jatt Da",
        movieName: "N/A",
      },
      {
        id: 6,
        singersName: "Diljit Dosanjh",
        duration: "3:17",
        songName: "Raat Di Gedi",
        movieName: "N/A",
      },
      {
        id: 7,
        singersName: "Diljit Dosanjh",
        duration: "3:54",
        songName: "Ikk Kudi",
        movieName: "Udta Punjab",
      },
      {
        id: 8,
        singersName: "Diljit Dosanjh",
        duration: "3:08",
        songName: "Patiala Peg",
        movieName: "N/A",
      },
      {
        id: 9,
        singersName: "Diljit Dosanjh",
        duration: "3:37",
        songName: "High End",
        movieName: "N/A",
      },
      {
        id: 10,
        singersName: "Diljit Dosanjh",
        duration: "4:02",
        songName: "G.O.A.T.",
        movieName: "N/A",
      },
      {
        id: 11,
        singersName: "Diljit Dosanjh",
        duration: "3:44",
        songName: "Born To Shine",
        movieName: "N/A",
      },
      {
        id: 12,
        singersName: "Diljit Dosanjh",
        duration: "3:29",
        songName: "Jind Mahi",
        movieName: "Shadaa",
      },
      {
        id: 13,
        singersName: "Diljit Dosanjh",
        duration: "3:55",
        songName: "Gabru Nu",
        movieName: "Super Singh",
      },
    ],
  },
];
